version: '3.8'

services:
  besu:
    image: hyperledger/besu:25.3.0
    container_name: besu-node
    command:
      - --data-path=/data
      - --rpc-http-enabled=true
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-cors-origins=*
      - --rpc-http-api=ETH,NET,WEB3
      - --host-allowlist=*
      - --miner-enabled=true
      - --miner-coinbase=0xb798b740a9649aa76fc01207926c40fb23f2eb35
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./node1:/data
    environment:
      - LOG_LEVEL=INFO